/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import classes.Animal;
import gerenciador.GerenciadorAnimal;

/**
 *
 * @author 15512921657
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        habilitarInfos(false);
        habilitarBusca(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        edtNome = new javax.swing.JTextField();
        edtEspecie = new javax.swing.JTextField();
        edtRaca = new javax.swing.JTextField();
        edtIdade = new javax.swing.JTextField();
        edtPeso = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        lblRaca = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalvos = new javax.swing.JTextArea();
        edtFind = new javax.swing.JTextField();
        lblBusca = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setName("Main"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro Animal");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 48, -1, -1));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 100, 35));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 100, 35));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 100, 35));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 100, 35));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 100, 35));
        jPanel1.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 270, -1));
        jPanel1.add(edtEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 270, -1));
        jPanel1.add(edtRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 270, -1));
        jPanel1.add(edtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 270, -1));

        edtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPesoActionPerformed(evt);
            }
        });
        jPanel1.add(edtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 270, -1));

        lblNome.setText("Nome:");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        lblEspecie.setText("Especie:");
        jPanel1.add(lblEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        lblRaca.setText("Raça:");
        jPanel1.add(lblRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        lblIdade.setText("Idade:");
        jPanel1.add(lblIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        lblPeso.setText("Peso:");
        jPanel1.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        txtSalvos.setEditable(false);
        txtSalvos.setColumns(20);
        txtSalvos.setRows(5);
        jScrollPane1.setViewportView(txtSalvos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 388, 150));
        jPanel1.add(edtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 270, -1));

        lblBusca.setText("Nome do cadastro");
        jPanel1.add(lblBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        btnFind.setText("->");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel1.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 600));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Felicidade.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 270, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPesoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        save(acao);
        apagarDados();
        habilitarInfos(false);
        imprimeNaTela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        habilitarBusca(true);
        acao = "Excluindo";
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitarInfos(false);
        habilitarBusca(false);
        apagarDados();
        acao = "Novo";
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitarBusca(true);
        habilitarInfos(false);
        acao = "Editando";
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        apagarDados();
        habilitarInfos(true);
        habilitarBusca(false);
        acao = "Novo";
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        if (animalBuscado(edtFind.getText()) != null) {

            if (acao.equals("Editando")) {
                habilitarBusca(false);
                habilitarInfos(true);
                preencheDados();
            } else {
                apagarCadastro();
                contador--;
                if (animais.getAnimais().size() == 0) {
                    txtSalvos.setText("");
                }
                apagarDados();
                habilitarInfos(false);
                habilitarBusca(false);
                acao = "Novo";
            }
        }
    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtEspecie;
    private javax.swing.JTextField edtFind;
    private javax.swing.JTextField edtIdade;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPeso;
    private javax.swing.JTextField edtRaca;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtSalvos;
    // End of variables declaration//GEN-END:variables

    private GerenciadorAnimal animais = new GerenciadorAnimal();
    private int contador = 0;
    private String acao = "Novo";

    public void habilitarInfos(boolean estado) {
        edtNome.setVisible(estado);
        edtEspecie.setVisible(estado);
        edtRaca.setVisible(estado);
        edtIdade.setVisible(estado);
        edtPeso.setVisible(estado);

        lblNome.setVisible(estado);
        lblEspecie.setVisible(estado);
        lblRaca.setVisible(estado);
        lblIdade.setVisible(estado);
        lblPeso.setVisible(estado);
    }

    public void apagarDados() {
        edtNome.setText("");
        edtEspecie.setText("");
        edtRaca.setText("");
        edtIdade.setText("");
        edtPeso.setText("");
        edtFind.setText("");
    }

    public Animal campoDoObjeto() {
        if (acao.equals("Novo")) {
            contador++;
        }
        String nome = edtNome.getText();
        String especie = edtEspecie.getText();
        String raca = edtRaca.getText();
        String idadeStr = edtIdade.getText();
        String pesoStr = edtPeso.getText();

        int idade = Integer.parseInt(idadeStr);
        double peso = Double.parseDouble(pesoStr);

        Animal anim = new Animal(contador, nome, especie, raca, idade, peso);

        return anim;
    }

    public Animal animalBuscado(String nomeBuscado) {
        for (Animal anim : animais.getAnimais()) {
            if (nomeBuscado.equals(anim.getNome())) {
                return anim;
            }
        }
        return null;
    }

    public void editarAnimal() {
        animais.Editar(animalBuscado(edtFind.getText()), campoDoObjeto());
    }

    public void habilitarBusca(boolean flag) {
        edtFind.setVisible(flag);
        lblBusca.setVisible(flag);
        btnFind.setVisible(flag);
    }

    public void save(String modo) {
        if (modo.equals("Novo")) {
            animais.addAnimal(campoDoObjeto());
        }

        if (modo.equals("Editando")) {
            editarAnimal();
        }

    }

    public void imprimeNaTela() {
        txtSalvos.setText(animais.imprimirAnimais());
    }

    public void preencheDados() {
        edtNome.setText(animalBuscado(edtFind.getText()).getNome());
        edtEspecie.setText(animalBuscado(edtFind.getText()).getEspecie());
        edtRaca.setText(animalBuscado(edtFind.getText()).getRaca());
        edtIdade.setText(String.valueOf(animalBuscado(edtFind.getText()).getIdade()));
        edtPeso.setText(String.valueOf(animalBuscado(edtFind.getText()).getPeso()));
    }

    public void apagarCadastro() {
        animais.getAnimais().remove(animalBuscado(edtFind.getText()));
    }

}
